

import 'dart:async';
import 'dart:ffi';
import 'dart:io';

String ?SelectedGender;
String ?SelectedLocation;
String ?SelectedMtachMakerExperience;
String ?SelectedDate;
DateTime? startdate;
String? datestring;
 File ?imgFile;
 String?Matchtype;
 String?match_with_id;
 String?match_from_id;
 String?Requeststatus;
 String? Ocupasion;
String verification_method="nationality_identity_card";
String?nationality;
File? ImagetoUpload;
String?Subcriptiontype;
  bool isSpinTimerVisible = false;
String?choose;
String ?listAsString;
String ?roomid;
  List<File> galleryImageFiles = [];
List <String>  interests=[];
  String? selectGender;
    bool isVisible = true;
  bool isNotVisible = false;
int rolevalue=1;
File? videoFile;
 int ?selectedseekerid;
  String? selectExperience;
String ?match_fromid;
String ?match_withid;
String?chatimage;
String?chatname;
String?chatimage1;
String?chatname1;
String ?Makerid;
String ?Sikeraddress;
String? BioTitle;
String? BioDescription;
String? IntrestedIn;
String? Interests;
String ?SikerReligon;
String selectedCountry = '';
String? userIdsiker;
String? requestIdsiker;
String? requestid;
String requestype="1";
String?action_with;
String?action_from;
String?actiontype;
Bool ?liverpullrequested;
Bool ?spinnwillrequested;
  DateTime? startTime;
  DateTime? endTime;
int selectedRadioTile=0;

bool islivierpooled=false;
bool isspinedwill=false;